package com.roassensor.sdk

import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Byte-for-byte parity with the backend `apps/tracking/security.py`. The expected
 * values were generated by calling `hash_email` / `hash_phone` directly on the
 * server, so this test fails the moment the Kotlin normalization drifts from the
 * Python one — the exact silent-mismatch this guards against.
 *
 * Regenerate the vectors with:
 *   PYTHONIOENCODING=utf-8 python -c "from apps.tracking.security import *; \
 *     print(hash_email('...'), hash_phone('...'))"
 */
class HashingParityTest {

    @Test
    fun email_matches_the_backend() {
        assertEquals(
            "6a6c26195c3682faa816966af789717c3bfa834eee6c599d667d2b3429c27cfd",
            Hashing.hashEmail("  Buyer@Example.COM "), // trims + lowercases
        )
        assertEquals(
            "bdb94ffa4890be68a8e80f9eacfbd322bb91fd1b39ceb76bc5213532e8879367",
            Hashing.hashEmail("test@roas.dev"),
        )
    }

    @Test
    fun phone_matches_the_backend() {
        assertEquals(
            "9e1919ad78a34fd67a84bfbcf2fea14074065517bea32e92924771c3f92e5462",
            Hashing.hashPhone("+1 (415) 555-0132"), // → +14155550132
        )
    }

    @Test
    fun arabic_indic_digits_fold_to_the_same_hash_as_ascii() {
        // A phone typed on a non-Latin keypad must hash identically, or the
        // identity bridge silently fails. U+0660–0669 → ASCII 0–9.
        val arabic = "٠٥٠١٢٣٤٥٦٧" // 0501234567
        assertEquals(Hashing.hashPhone("0501234567"), Hashing.hashPhone(arabic))
        assertEquals(
            "01cc498c268a4314d231f2e899a9faf717b7f8bbc9f3889bb1e539651907adde",
            Hashing.hashPhone(arabic),
        )
    }

    @Test
    fun too_short_phone_is_not_a_key() {
        assertEquals("", Hashing.hashPhone("123")) // < 7 digits → empty
    }
}
